/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as MotoristasFrotaRouteImport } from './routes/motoristas-frota'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesStatusOperacionaisRouteImport } from './routes/configuracoes.status-operacionais'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPreparacaoRouteImport } from './routes/admin.preparacao'

const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasFrotaRoute = MotoristasFrotaRouteImport.update({
  id: '/motoristas-frota',
  path: '/motoristas-frota',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesStatusOperacionaisRoute =
  ConfiguracoesStatusOperacionaisRouteImport.update({
    id: '/configuracoes/status-operacionais',
    path: '/configuracoes/status-operacionais',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreparacaoRoute = AdminPreparacaoRouteImport.update({
  id: '/admin/preparacao',
  path: '/admin/preparacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/motoristas-frota': typeof MotoristasFrotaRoute
  '/planejamento': typeof PlanejamentoRoute
  '/admin/preparacao': typeof AdminPreparacaoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/configuracoes/status-operacionais': typeof ConfiguracoesStatusOperacionaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/motoristas-frota': typeof MotoristasFrotaRoute
  '/planejamento': typeof PlanejamentoRoute
  '/admin/preparacao': typeof AdminPreparacaoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/configuracoes/status-operacionais': typeof ConfiguracoesStatusOperacionaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/motoristas-frota': typeof MotoristasFrotaRoute
  '/planejamento': typeof PlanejamentoRoute
  '/admin/preparacao': typeof AdminPreparacaoRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/configuracoes/status-operacionais': typeof ConfiguracoesStatusOperacionaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/auditoria'
    | '/diagnostico'
    | '/motoristas-frota'
    | '/planejamento'
    | '/admin/preparacao'
    | '/admin/usuarios'
    | '/configuracoes/status-operacionais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/auditoria'
    | '/diagnostico'
    | '/motoristas-frota'
    | '/planejamento'
    | '/admin/preparacao'
    | '/admin/usuarios'
    | '/configuracoes/status-operacionais'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/auditoria'
    | '/diagnostico'
    | '/motoristas-frota'
    | '/planejamento'
    | '/admin/preparacao'
    | '/admin/usuarios'
    | '/configuracoes/status-operacionais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AuditoriaRoute: typeof AuditoriaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  MotoristasFrotaRoute: typeof MotoristasFrotaRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  AdminPreparacaoRoute: typeof AdminPreparacaoRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  ConfiguracoesStatusOperacionaisRoute: typeof ConfiguracoesStatusOperacionaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas-frota': {
      id: '/motoristas-frota'
      path: '/motoristas-frota'
      fullPath: '/motoristas-frota'
      preLoaderRoute: typeof MotoristasFrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/status-operacionais': {
      id: '/configuracoes/status-operacionais'
      path: '/configuracoes/status-operacionais'
      fullPath: '/configuracoes/status-operacionais'
      preLoaderRoute: typeof ConfiguracoesStatusOperacionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preparacao': {
      id: '/admin/preparacao'
      path: '/admin/preparacao'
      fullPath: '/admin/preparacao'
      preLoaderRoute: typeof AdminPreparacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AuditoriaRoute: AuditoriaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  MotoristasFrotaRoute: MotoristasFrotaRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  AdminPreparacaoRoute: AdminPreparacaoRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  ConfiguracoesStatusOperacionaisRoute: ConfiguracoesStatusOperacionaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
